### ISSUE TITLE
Setting different resolution for my main Monitor when csgo.exe is launched

### ISSUE THREAD

**Issue by Killberty** [juvlarN/vibranceGUI#11]
Hey devs,

first off great work, i use it every day an it is truely amazing.

The csgo.exe detection is working perfectly so i would like to have a featire added (if possible) rather than using another, second program for this.

I prefer playing csgo in borderless fullscreen, so i can tab to my other two monitors quickly, but i really want to play in 4:3 1400x1050.

So my question is: can you also add a funtion to change resolution of a certain monitor when csgo is detected and cange it back when it is closed?

Greets and thanks
Pascal
(Using NVIDIA if that matters)

**Comment by juvlarN** [comment]
Hi,

this might actually be possible and not much work when NVIDIA finally decides to give me access to their NDA version of the NVAPI. The NDA version of the NVAPI offers a lot of functions which the normal API does not have access too. Things like the one you mentioned could be added quite easily. Reference: https://github.com/juvlarN/vibranceGUI/issues/8 

When not having access, it's too much work for something that only a few people would use to be honest. But I'm not throwing you off yet, I might add this whenever I get the NDA version. 

Greets

**Comment by Killberty** [comment]
What version of NVAPI do you have? i have acces to R352.

**Comment by juvlarN** [comment]
Do you mean R352 of the public API or the NDA API? 
The public API is of little to no use.

**Comment by Killberty** [comment]
File name is R352-developer.zip
I am only hobby dev (java and versy little C#) and i dont understand nothing but if oyu want to take a look into it give me your mail adress.

**Comment by juvlarN** [comment]
Does it contain "NvAPI-NDA.pdf"? If not, it's not right.

**Comment by Killberty** [comment]
Nope, sorry :(

what about this:
https://code.google.com/p/evolution3d/source/browse/trunk/Devel/Plugin/NvRenderer/NvApi/?r=3

**Comment by juvlarN** [comment]
its heavily outdated

**Comment by Killberty** [comment]
Yeah i saw that...

Good luck on getting the latest version then :)

**Comment by Killberty** [comment]
Hey @juvlarN,

as it doesnt seem to be possible to ghet acces to nvidias nda nvapi, i did some research and found this: http://blog.start-automating.com/updates/How%20to%20change%20the%20monitor%20resolution%20in%20Powershell/

can you implement my feature request by doing this? should be easy, right?

**Comment by Killberty** [comment]
Found something even better:
http://www.codeproject.com/Articles/36664/Changing-Display-Settings-Programmatically

Please implement an automatic resolution changer <3

**Comment by juvlarN** [comment]
This has been added in the meantime: https://github.com/juvlarN/vibranceGUI/tree/Dynamic_VibranceGUI
