### ISSUE TITLE
issue when browsing /r/GlobalOffensive

### ISSUE THREAD

**Issue by commit-sudoku** [juvlarN/vibranceGUI#12]
So I'm assuming the way this program works is by waiting for the current focused window to be titled "Counter-Strike: Global Offensive" and then changing the digital vibrance once it is found.

The problem I have is that when I view the main page of /r/GlobalOffensive, my browser window is titled "Counter-Strike: Global Offensive" and vibranceGUI kicks in.

**Comment by Kazarp** [comment]
@commit-sudoku this should be fixed in the new beta release

**Comment by mike-u** [comment]
This is actually pretty funny.

**Comment by juvlarN** [comment]
This has been fixed for a while now. I'm closing this issue.
