### ISSUE TITLE
vibranceGUI isn't working for my game

### ISSUE THREAD

**Issue by m1nhhh** [juvlarN/vibranceGUI#14]
I am currently running a xl2411z BenQ 144hz monitor and an older Samsung monitor for my duo monitor setup. Once I go in game, my vibranceGUI does not affect my color, I play on fullscreen 1024x768 black bars. I would like to fix this so I could play ESEA with nicer vibrant colors. I was previously using SweetFX.

**Comment by juvlarN** [comment]
Sorry for the delayed response, is this still happening?
Have you tried the version that has been released on my twitter?

**Comment by juvlarN** [comment]
I guess this is resolved?
