### ISSUE TITLE
VGUI running in background disables auto-hide

### ISSUE THREAD

**Issue by SammyTheBEAST** [juvlarN/vibranceGUI#15]
I have an auto-it script that turned on VGUI when CSGO opens, the only problem is when its running in the background it stops my taskbar from auto-hiding. Is there a way to fix this or can you add a "have VGUI run in background" option?

**Comment by Kazarp** [comment]
Can you please paste the auto-it script?

>it stops my taskbar from auto-hiding
Does it mean that your taskbar is visible in CSGO?

Does it happen only when VGUI is running in the background?

It is probably an auto-it issue, but if you give more info, I'll look into it.

**Comment by juvlarN** [comment]
Is this still an issue?
