### ISSUE TITLE
Other Applications

### ISSUE THREAD

**Issue by Duwayne6** [juvlarN/vibranceGUI#17]
You should add the ability to add other applications to a list that the application monitors, so we can use it for other applications besides CSGO.

Thanks!

**Comment by juvlarN** [comment]
This is already released as a beta version. Check my twitter account @juvlarn for a download link.

**Comment by Duwayne6** [comment]
Does this beta version set NV @ 100% it don't have a slider like the "current version".

I snagged the 2.1 BETA.

**Comment by juvlarN** [comment]
Double press the icon of the game you added.
A new slider window specifically for that game will pop up. Gotta make that a little bit more clear I guess. :-)

**Comment by Duwayne6** [comment]
Ah! that worked. thanks!!! this is exactly what i was after.. Thanks!

**Comment by Duwayne6** [comment]
The "set your own delay" functionality isn't in this version is it? i can't find it. (i had it set to 30 seconds per check to reduce stutter possibility)

**Comment by juvlarN** [comment]
No this is not needed anymore. The Application now listens for window change events from Windows. This should be using even less performance than the version from the website (no matter what delay you set). The change of the vibrance level is also instant now. As long as your graphic card can keep up, vibrancy should already be changed when you are about to alt+tab. 

I'm closing this. Have fun with the program. More features coming soonish.
