### ISSUE TITLE
Is there a possibility for a version where I can choose to monitor multiple programs?

### ISSUE THREAD

**Issue by Hoshiyuu** [juvlarN/vibranceGUI#2]
There are plenty of other games that could benefit from the auto-toggle of DVC between desktop and in-game, can the app be updated in a way that I can add list of programs into a drop down menu?

**Comment by Hoshiyuu** [comment]
@juvlarN Hey, its been a while, just thought I would stop by and ask again on any chance of manually adding support for other games?

**Comment by juvlarN** [comment]
@Hoshiyuu you can manually add the support for other games by adjusting the needed strings in the projects. All you need to do is to replace the window name of cs:go ("Counter-Strike: Global Offensive") to the window name you want. You also need to build the vibranceDLL project with adjusted strings if you want to use the NVIDIA version. After that, you have a version built for your specific program. Its actually not that much of an effort. You will need an IDE like Visual Studio though. 

I don't know what you mean with your last sentence. You can manually adjust the digital vibrance value in the NVIDIA Control Panel? Display -> Desktop Color Settings -> 3. Digital Vibrance is where you can find it.

**Comment by juvlarN** [comment]
This has been implemented in the meantime.
