### ISSUE TITLE
Making this work for other application/games

### ISSUE THREAD

**Issue by theowner997** [juvlarN/vibranceGUI#20]
Not really an issue, more of question.
Is there any way I can make this work for other games when they are launched?
Or if you are interested, you can make it, so people add the games into a game list and when they are launched it does the same thing.
I am an AMD user, I miss the hotkeys from the catalyst drivers.

**Comment by theowner997** [comment]
I know some advanced Java and basic things in C# 

Is there a possibility for the program to check for more than the csgo proccess ? Like iw4mp.exe in my case etc etc.
I can help you If I can.
for example

if (csgo.exe ..... ) then blah blah
if (iw4mp.exe ... ) then blah blah 

If you dont want to implement it this way, can you show me at least how can I do it?

Great program by the way!

**Comment by juvlarN** [comment]
Hi,

this is already implemented in branch Dynamic_VibranceGUI (https://github.com/juvlarN/vibranceGUI/tree/Dynamic_VibranceGUI) and also published as a beta version on my twitter for NVIDIA users. The AMD version was previously coded by @juRiii but he's a lazy boy so it might take some more time. 

Greets

**Comment by theowner997** [comment]
So I checked twitter and everything , and the AMD guys seems very inactive,so until the guy releases the AMD version with the game list, I would like to implement code that checks for more than just the csgo.exe . And if the program finds at least one of the games running, then do the saturation stuff.

The problem is, I am not a C# guy, I know Java though which is very similar.
Any way showing me, how to implement that? Cause I checked the code last night and I just couldn't find where the checking part for the csgo proccess is.

**Comment by juliuszint** [comment]
I looked trough the code and it seems (at least for the NVIDIA part) that in the `NvidiaVibranceProxy` class there is a Dll imported Method `isCsgoActive` that does the check wheter csgo is running or not but the source for the Dll is not shipped! To make the code consistent (and not work around) one would have to modify the vibranceGUI.dll. Is there a possibility @juvlarN that you could include the vibranceGUI.dll source?

**Comment by juvlarN** [comment]
@theowner997 
For AMD, you could start off by changing "Counter-Strike: Global Offensive" to whatever window title you want  [here](https://github.com/juvlarN/vibranceGUI/blob/master/vibrance.GUI/AMD/vendor/mvvm/viewmodel/VibranceSettingsViewModel.cs). I'm not totally sure about the code flow for the AMD version but stepping through the code with the debugger will give you enough insight anyways. 

@juliuszint 
The Proxy dll is a different project, located at [vibranceDLL](https://github.com/juvlarN/vibranceDLL). As mentioned above, there is a dynamic version that is able to manage any program you want for NVIDIA already.
Concerning `isCsgoActive`: The method name is a bit misleading as it checks whether the passed window handle is being displayed in foreground. This is still a leftover from when vibranceGUI was heavily wired to CS:GO as it was not my intention to release the program when I started the project. I'll fix the method name in a few minutes.

**Comment by theowner997** [comment]
Seems the AMD guy has lost interest or something.
Anyway, If anyone can help me make the program check for more games and not only CSGO, let me know. No GUI or game list just background checking.

**Comment by juvlarN** [comment]
The new versions contain AMD support for any application.
You can build the program yourself or download the beta binaries from [here](http://vibrancegui.com/vibrance/beta)
