### ISSUE TITLE
Updates/Versioning

### ISSUE THREAD

**Issue by harrymilne** [juvlarN/vibranceGUI#27]
I tried looking but found no evidence of a version number for different releases. How am I supposed to tell if I need to download a new binary? I looked at the 'Date Modified' on Windows and could see that a new binary had been built but that isn't a very effective way of telling if an update is available.

Not sure if this project is still in development but it'd be nice to see just an 'about' button or something to just tell me which version I have.

**Comment by juvlarN** [comment]
Hello @harrymilne,

you can find a version number in the properties (tab "details") of the exe file. 
The current beta has a version number of 2.2.0.0. 
The version number has been increased from 1.x.x.x to 2.x.x.x when switching from the csgo-only vibranceGUI to the dynamic version that can handle any application. The dynamic version is available on my twitter (@juvlarn) for now until we resolve some bugs that are left over.

Updates usually only get announced on my twitter. Major updates might be posted on reddit afterwards by users though.

**Comment by harrymilne** [comment]
I feel stupid now. 👍 

Thanks. 😂
