### ISSUE TITLE
I believe vibranceGUI is lowering my Windows volume

### ISSUE THREAD

**Issue by nadadepao** [juvlarN/vibranceGUI#31]
Whenever I alt-tabbed out of CS:GO, my volume would lower a lot (even though in the mixer it was at max volume level) and my microphone would stop working, and the only fix for that was unplugging and plugging my headset back.
I exited vibranceGUI, started CS:GO, alt-tabbed, and everything is fine, that's why I believe it was vibranceGUI causing the problem.

**Comment by juvlarN** [comment]
Well, obviously vibranceGUI has no code implemented that interacts with your microphone or the Windows settings that control the volume of your input/output devices. 

Make sure you have this setting checked:
Right click the "Sound" icon in your Windows taskbar on the far right, select Input Devices, select Tab "Communication", select option "Disable" (roughly translated). And see if it works.

Btw, Razer Synapse is known to cause problems with vibranceGUI. Maybe this might be running on your PC too. Not sure if it fixes this specific problem though.

**Comment by juvlarN** [comment]
Any update on this?

**Comment by nadadepao** [comment]
I don't remember whether was vibranceGUI doing that, but currently, everything is fine. You can close this issue if you want.
