### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Bilinodas** [juvlarN/vibranceGUI#34]
hi, i've been using vibrancegui for a long time and today when I started csgo it wasn't working. So i already checked the video settings because i know multisampling desactivates vibrancegui. The real problem is that vibrance gui affects my game when its window mode and doesnt when it's fullscreen.

**Comment by juvlarN** [comment]
Hi, check this issue please: https://github.com/juvlarN/vibranceGUI/issues/35
