### ISSUE TITLE
Vibrance gui monitor problem

### ISSUE THREAD

**Issue by Mraft** [juvlarN/vibranceGUI#37]
So i installed vibrance gui and suddenly it changed my monitor graphics to shit and colors to more shiny. Does some1 knows how to solve it? PS: i dont want to reinstall my windows

**Comment by juvlarN** [comment]
Please describe more in depth what happened. 
When you change your Windows vibrance level to more than 50% on NVIDIA and 100% on AMD, the colors will obviously change.
Just by starting the program, you should not see any difference.
