### ISSUE TITLE
AMD card is detected when there is none installed

### ISSUE THREAD

**Issue by vikenemesh** [juvlarN/vibranceGUI#38]
The window title says "AMD" although there is a NVidia card in my system right now. I previously had an AMD card installed, but not right now.

Is there an option to force the option? Or can you adjust the detection?

**Comment by juvlarN** [comment]
You did not uninstall your AMD drivers then.
Download an AMD driver uninstaller tool, the official one does not delete all files.
Make sure you do not have "atiadlxx.dll" and/or "atiadlxy.dll" in your Windows folder anymore.
Rename / Move / Delete those files.

**Comment by vikenemesh** [comment]
The official "AMD Clean Uninstall Utility"solved it. Seems like the normal uninstaller can't manage to do it properly, like you said. Thanks.
