### ISSUE TITLE
Enhancement for AMD Cards

### ISSUE THREAD

**Issue by Lynx23** [juvlarN/vibranceGUI#4]
Hi juvlarN, i'm using your tool with my old GTX 260 and i'm lovin it. But as to a due pc update i will change to a R9 280 because of cost effectiveness. Could you possibly enhance your tool with AMD support? Else i would really miss sth. 

TIA, Lynx

**Comment by juRiii** [comment]
Check this out: https://twitter.com/juvlarN/status/562750038506737667

Could you test this version?

**Comment by juvlarN** [comment]
@Lynx23 have you tested the AMD version?

**Comment by juvlarN** [comment]
Closing this as the AMD support has been added.
