### ISSUE TITLE
VibranceGUI issue 

### ISSUE THREAD

**Issue by M3dik** [juvlarN/vibranceGUI#46]
Hey juvlarN,
I have issue with VibranceGUI. 
It's change colors of the game but, it isn't that strong how it should be
PLEASE HELP!!! 
(Yes I have it to 100%)

**Comment by juvlarN** [comment]
100% is max for nvidia, you can't get higher.
What do you mean "how it should be"? Its depending on monitor settings, other GPU driver settings etc...

**Comment by M3dik** [comment]
Its not giving me strong colors

**Comment by M3dik** [comment]
its just lighter

**Comment by juvlarN** [comment]
If you see a difference between for example 50% and 100%, it is working as intended.
Note that vibranceGUI itself has no control how strong the colors are. This is bound to your GPU driver. vibranceGUI just automates these GPU settings for your convenience so you do not need to manually change it in your GPU driver program every time you switch out of a game into windows etc.
