### ISSUE TITLE
VibrancaGUI is not giving me good Vibrance 

### ISSUE THREAD

**Issue by M3dik** [juvlarN/vibranceGUI#49]
Hello juvlarN!
VibranceGUI is not giving me good Vibrance. 
I have it on 100% but the game is not that nice like it should be it just lighter.
Can u help me with that?

**Comment by juvlarN** [comment]
Elaborate on "like it should be"? 
100% is the maximum on NVIDIA. There is no way to get more than 100% on NVIDIA gpus as the driver limits the digital vibrance level. 
When you mean your colors are less vibrant than the ones you see on Twitch, keep in mind that streamers use dedicated capturing cards which will add another % of color vibrancy. The streamers themselves do not see the additional color that you see on the stream. 

As 100% is the maximum for NVIDIA, you should consider switching your monitor settings as these are independent of your GPU settings.

**Comment by M3dik** [comment]
Where can I switch it? Can you help me with that?

**Comment by juvlarN** [comment]
You change the settings at the monitor itself. You should see settings like "Brightness", "Saturation", "Contrast" and the like. Adjust them so it fits your needs.

I have a BenQ XL2420Z, which has an additional "remote control" next to the monitor stand.
With this "remote control" I can switch between setting mode 1 / 2 / 3. Maybe your monitor has a similar control, which makes it easy to switch between settings for normal Windows usage and In-Game usage.

**Comment by M3dik** [comment]
Thx dude its helped <3
