### ISSUE TITLE
VibranceGUI affects secondary screen 

### ISSUE THREAD

**Issue by lesjj** [juvlarN/vibranceGUI#53]
Hey, 

VibranceGUI is affecting my second monitor while im not in any game, just in windows. I got Nvidia graphics card btw. When I switched off the option "Affect primary monitor only" it went away and when I turned it on again it was still okay. My second screen is not my primary monitor btw. Besides that VirbanceGUI also gives me still the message from another issue -> "Changing the resolution failed: DispChangeBadmode". I've read this in an older topic (https://github.com/juvlarN/vibranceGUI/issues/36)

**Comment by juvlarN** [comment]
Have you tried the Beta already? [vibrancegui.com/vibrance/beta](vibrancegui.com/vibrance/beta)

**Comment by lesjj** [comment]
Nope! Gonna try it now, thanks. Update your website plz :) (Very old version online)

**Comment by juvlarN** [comment]
Have you tried it in the meantime?

**Comment by lesjj** [comment]
Beta worked! Thanks

Met vriendelijke groet,

Lesley Hermsen
E-mail: l.hermsen92@live.nl<mailto:l.hermsen92@live.nl>

---- juvlarN schreef ----


Have you tried it in the meantime?
