### ISSUE TITLE
Cant change resulution when VibranceGUI is active

### ISSUE THREAD

**Issue by pCoder3000** [juvlarN/vibranceGUI#57]
i have a 1060 6gb and my drivers are up to date

**Comment by juvlarN** [comment]
I also can't change my resolution in the NVIDIA driver. It does not seem to relate to vibranceGUI though. When I untick autostart in vibranceGUI, reboot, try to change the resolution in the NVIDIA driver, nothing happens as well. 

However, when I use the Windows resolution changer (in the Windows display options menu)  it does work - with and without vibranceGUI running.

**Comment by pCoder3000** [comment]
I got the problem only with Fortnite ...
And i was able to chage my resolution when i turend vibranceGUI off :P

**Comment by juvlarN** [comment]
I will need steps to reproduce this then. I can't seem to reproduce this error

**Comment by pCoder3000** [comment]
When i chage my resolution over Windows display options the fps is locked to 60 and in my NVIDIA driver shows me that my resolution is UHD  
![grafik](https://user-images.githubusercontent.com/35534230/35120728-6149dc8a-fc99-11e7-8a9a-7eeae656e266.png)

**Comment by pCoder3000** [comment]
yeah mabe i can try it again

**Comment by juvlarN** [comment]
This is weird. The driver should not do that, it works fine for me as well. 
Try to set the resolution in Windows menu (set hz higher than 60). 
Run cmd.exe and type
`wmic PATH Win32_videocontroller get currentrefreshrate` 
This will show your current refresh rate. And see if it correctly set the refresh rate.
If it does, then your nvidia driver seems to be buggy. Run [Display Driver Uninstaller](http://www.guru3d.com/files-details/display-driver-uninstaller-download.html) and install a fresh version of the NVIDIA driver afterwards.

**Comment by pCoder3000** [comment]
All right here
![grafik](https://user-images.githubusercontent.com/35534230/35120908-eec72b44-fc99-11e7-8ccf-088d36fa0507.png)
all normal here too 
![grafik](https://user-images.githubusercontent.com/35534230/35120966-1c196cce-fc9a-11e7-8b44-a9aa35c8fe6a.png)

mhh since the new update from Fortnite this glitch dident happend again :/ 👍

**Comment by pCoder3000** [comment]
thx you <3

**Comment by juvlarN** [comment]
Alright, so is this resolved?

**Comment by pCoder3000** [comment]
i think so i will call you when it happens again 👍

**Comment by pCoder3000** [comment]
mabe you know why my gtx has 2 1080 p modes 1 with UHD and one without ? xD
![grafik](https://user-images.githubusercontent.com/35534230/35121245-1009a952-fc9b-11e7-9858-8c71d341d7e2.png)
![grafik](https://user-images.githubusercontent.com/35534230/35121295-3521b9d2-fc9b-11e7-89ed-4f42fa6f497e.png)

**Comment by juvlarN** [comment]
If I recall correctly, you should use the "PC resolutions". No idea why there are these Ultra-HD resolutions.

**Comment by pCoder3000** [comment]
the pc resolutions work for me but i think some games and somtimes shadowplay switch them to the Ultra-HD resolutions and they are laggy.
The whole name is stupid Ultra-HD 1080p xD

**Comment by pCoder3000** [comment]
got problem again ;P cant chage resolution back while vibrace is running ;P

**Comment by camjac251** [comment]
For me this problem occurs as well.

I've reinstalled my drivers many times before and even replaced the displayport cable thinking that it was faulty but what happens for me is that (at least I think) after running a game that is added to vibrancegui and closing it, then either in the nvidia control panel or windows settings, you can't change the resolution or refresh rate of the monitor. It will change for a sec with the monitor going out but then default back to the settings it was on before. Only after closing vibranceGUI did it allow me to change the resolution and refresh rate.

**Comment by juvlarN** [comment]
@camjac251 can you work out a step-by-step explanation on how to reproduce this issue?
