### ISSUE TITLE
Does not work with Intel NUC and AMD Radeon Vega Graphics

### ISSUE THREAD

**Issue by incognico** [juvlarN/vibranceGUI#68]
The new Intel NUC8I7 uses AMD Radeon Vega Graphics which comes with a Intel branded AMD Adrenaline driver GUI. Vibrance GUI does not seem to work here.

DxDiag: http://dpaste.com/1NR67JV

Driver: https://downloadcenter.intel.com/download/27723/NUCs-Radeon-Graphics-Driver-for-Intel-NUC-Kit-NUC8i7HNK-NUC8i7HVK?product=126143

**Comment by juvlarN** [comment]
Try this https://github.com/juvlarN/vibranceGUI/issues/19#issuecomment-356444493

**Comment by incognico** [comment]
That will only work for intel gpus not AMD ones. The Intel iGPU is permanently disabled on the NUC and only the AMD Vega is used.

**Comment by juvlarN** [comment]
Elaborate on the "does not seem to work" then

**Comment by incognico** [comment]
Hm, it does work it seems. It is a bit weird. The windows vibrance for example will only get applied after the program was closed. After reopening it and opening a defined app it did what it should.

I also noticed that my mouse pointer lags for like 5 seconds after opening the program.
