### ISSUE TITLE
Monitor Bug / Changes resolution and hertz

### ISSUE THREAD

**Issue by Keidaron** [juvlarN/vibranceGUI#69]
Greetings

Well I got the problem that when I use VibranceGUI that my second monitor goes from 1280x1024 up to 1920x1080 and goes to 59 hertz.

It is really annoying.

How does it appear ?
1. Starting Vibrancegui
2. Clicking on the Left Monitor to open windows startmenu
3. problem appears

**Comment by juvlarN** [comment]
Hi, please try this:

https://github.com/juvlarN/vibranceGUI/issues/56#issuecomment-384398934



Keidaron <notifications@github.com> schrieb am Mo. 21. Mai 2018 um 12:55:

**Comment by Keidaron** [comment]
It helped thanks!
