### ISSUE TITLE
Reset settings

### ISSUE THREAD

**Issue by GnidaKid69** [juvlarN/vibranceGUI#70]
Hello! I was using vibranceGUI about 1 week then I felt like colors were too saturated and wanted to turn it down games that I added weren't there anymore I tried to delete it completely but it didn't worked then I tried to add these games again and change settings but it didn't worked either. So now I want to get rid of this settings how to reset everything that VIbraceGUI changed?

**Comment by juvlarN** [comment]
Navigate to folder %appdata%/vibranceGUI and delete applicationData.xml
