### ISSUE TITLE
whitebalance/vibrance not resetting

### ISSUE THREAD

**Issue by basn** [juvlarN/vibranceGUI#71]
After csgo i always get really bad whitebalance when running vibrancegui.
I am unsure when it came but with latest drivers 397.93 and win10 1803 i get this issue.
I have to either reboot or reinstall drivers to be able to look at white pages etc.

I am not sure what do troubleshoot, is there anything i can try?

**Comment by juvlarN** [comment]
Have you tried a different driver version (older one that you used before)?

**Comment by basn** [comment]
seems like its drivers related, i get the error if i do vibrance from the drivers also... so its not from this..
