### ISSUE TITLE
AMD Sharpness

### ISSUE THREAD

**Issue by Penagwin** [juvlarN/vibranceGUI#9]
Sorry, I know other's are asking for somewhat similar things. I'll help if I can, although I have never used the adl sdk, or c# for that matter (Java is close enough right? :P).

[Would this maybe help?](https://htmlpreview.github.io/?https://github.com/elitak/amd-adl-sdk/blob/master/Public-Documents/html/display_8h.html)

**Comment by juvlarN** [comment]
@juRiii made the AMD version so he might take a look into it. But to be honest, I dont think there is enough demand for this. You can add this on your own and open a pull request afterwards. 
You can pull the master branch and add your changes to the AMD version. 
C# is pretty much like Java, you won't need much time getting used to it.
